### ISSUE TITLE
Execution of iep-miner-master

### ISSUE THREAD

**Issue by bcps4** [GitHug/iep-miner#1]
I have downloaded the code from the link https://github.com/GitHug/iep-miner and i have installed eclipse and the required software mentioned. When i try to run the program no output is shown.

I am keenly interested to explore and execute code.

There is another program called suffix tree in the link above but not able to integrate it and run the entire program.please give the detailed steps to execute the programs.

Thank you.

**Comment by NagaSubhash** [comment]
The same request from me either as @bcps4 !

i couldnt even link the stanfordpostagger! and i couldnt even get the datasets from yahoo..

it would be very helpful if you could help with it!

Thank you!

**Comment by armanmalik** [comment]
I have downloaded the code from the link https://github.com/GitHug/iep-miner and i have installed eclipse and the required software mentioned. When i try to run the program no output is shown.

I am keenly interested to explore and execute code.

Thank you!
it would be very helpful if you could help with it!

**Comment by armanmalik** [comment]
I have downloaded the code from the link https://github.com/GitHug/iep-miner and i have installed eclipse and the required software mentioned. When i try to run the program no output is shown.

I am keenly interested to explore and execute code.

please give the detailed steps to execute the programs.

Thank you.

**Comment by armanmalik** [comment]
@NagaSubhash could you plz give your email id ...iam having doubts so that i can clear with u

Thanks

**Comment by NagaSubhash** [comment]
@armanmalik  Its cnagasubhash@yahoo.com .. Thank You for your interest.. I am glad you could make it with me. :)

**Comment by GitHug** [comment]
Thank you for the interest in the application. The application will replaced in the near future with a better one that will also include better documentation for how to use it.
